Add Docker containers for Web Frontend and Web Backend
StraykerPL/Binder pull request #121
Opened 2023-11-10 22:37 UTC by Lukash88

## Summary

Create Docker containers for Web Frontend and Web Backend.

## Details

- Added Dockerfiles for Web Frontend and Web Backend,
- Added docker-compose.yml,
- Added app settings file with connection strings for Docker

Out of scope: Added image for database.

## References

No external references needed.

2023-11-10 23:44 UTC, StraykerPL requested changes

2023-11-10 23:44 UTC, StraykerPL commented on binder-web-frontend/Dockerfile
> +RUN npm run prepare-husky
This dev environment command, not needed in other environments - can be removed.

2023-11-10 23:51 UTC, Lukash88 commented on binder-web-frontend/Dockerfile
> +RUN npm run prepare-husky
Resolved d5a1f96.

2023-11-11 00:00 UTC, StraykerPL approved these changes

2023-11-11 00:00 UTC, merged