Error message is not appearing in web browser
StraykerPL/Binder pull request #129
Opened 2023-11-15 21:17 UTC by Lukash88

## Summary

Error messages are appearing in web browser (DevTools)

## Details

- Changes in  `ToDoTasks`  `Repository` and `Service`
- Error handling middleware refactored - swap  switch  expression to switch statement 
 and assigned  http response code to each response case

## References

No external references needed.

2023-11-15 21:26 UTC, StraykerPL requested changes

2023-11-15 21:26 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                ProblemDetails problemDetails;
Add null to declaration.

2023-11-15 21:26 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    case InvalidOperationException invalidOperationException:
There's no need to make case variable - use `e.Message`.

2023-11-15 21:26 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/ToDoTasksService.cs
> +            return _repository.GetTasksByTable(tableId) ?? throw new NotFoundException(ExceptionConstants.ResourceNotFoundMessage);
Why returned to old styling?

2023-11-15 21:27 UTC, StraykerPL commented
Please remember next time about commit name styling.

2023-11-15 21:27 UTC, StraykerPL commented
Please provide example screenshot to description.

2023-11-16 20:41 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                ProblemDetails problemDetails;
Resolved 60b5acc.

2023-11-16 20:41 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/ToDoTasksService.cs
> +            return _repository.GetTasksByTable(tableId) ?? throw new NotFoundException(ExceptionConstants.ResourceNotFoundMessage);
Back to  previous style.

Resolved 60b5acc.

2023-11-16 20:41 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    case InvalidOperationException invalidOperationException:
Resolved 60b5acc..

2023-11-18 22:55 UTC, StraykerPL approved these changes

2023-11-18 22:55 UTC, merged