Ioc container setup code
StraykerPL/Binder pull request #133
Opened 2023-11-26 21:59 UTC by Lukash88

## Summary

Refactor registration of IoC.

## Details

- Create virtual folder in **Binder.Api** project for extension classes,
- Create extension class for **Service** and **Repository** registration instructions,
- Create extension class for **Swagger** config code.

## References

No external references needed.

2023-11-26 22:25 UTC, StraykerPL requested changes

2023-11-26 22:25 UTC, StraykerPL commented on binder-web-backend/Binder.Api/Extensions/ApplicationServicesExtensions.cs
> +    public static class ApplicationServicesExtensions
Refactor to decouple relations with Persistance and Appliacation layer.

2023-11-26 22:25 UTC, StraykerPL commented on binder-web-backend/Binder.Api/Extensions/SwaggerServiceExtensions.cs
> +        public static IApplicationBuilder UseSwaggerDocumentation(this IApplicationBuilder app, IWebHostEnvironment env)
`IApplicationBuilder` and `IWebHostEnvironment` deliver same Environment value, no need for additional argument.

2023-11-27 22:07 UTC, Lukash88 commented on binder-web-backend/Binder.Api/Extensions/ApplicationServicesExtensions.cs
> +    public static class ApplicationServicesExtensions
Resolved a688c46.

2023-11-27 22:07 UTC, Lukash88 commented on binder-web-backend/Binder.Api/Extensions/SwaggerServiceExtensions.cs
> +        public static IApplicationBuilder UseSwaggerDocumentation(this IApplicationBuilder app, IWebHostEnvironment env)
Resolved a688c46.

2023-11-27 22:23 UTC, StraykerPL approved these changes

2023-11-28 05:39 UTC, merged