Swap MatAccordion to MatTree in Tables List component
StraykerPL/Binder pull request #138
Opened 2023-12-06 20:42 UTC by Lukash88

## Summary

Change MatAccordion to MatTree in Tables List component.

## Control List

- [x] Code formatting checked,
- [x] Coding Guidelines compliance checked,
- [ ] Documentation updated (if necessary),
- [ ] Automated tests updated (if necessary),

## Screenshots

Tables List expanded:
<img width="160" alt="image" src="https://github.com/Strayker-Software/Binder/assets/80634023/6f244e6d-a65e-4997-9160-3264ead77d88">

Tables List collapsed:
<img width="157" alt="image" src="https://github.com/Strayker-Software/Binder/assets/80634023/94fcda5a-0b03-46ca-9646-f05bc3cdeea9">

2023-12-06 22:25 UTC, StraykerPL requested changes
Change MatNestedTree to MatTree with flat nodes, refactor styles to make them more readable, check code formatting once more.

2023-12-10 23:50 UTC, StraykerPL requested changes

2023-12-10 23:50 UTC, StraykerPL commented on binder-web-frontend/src/api/model/tableFlatNode.ts
If this is your code, not generated, move to `shared/models` folder.

2023-12-10 23:50 UTC, StraykerPL commented on binder-web-frontend/src/api/model/tableNode.ts
Same here.

2023-12-10 23:50 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
> +      display: inline-flex;
Change to `flex` only.

2023-12-10 23:50 UTC, StraykerPL commented on binder-web-frontend/src/pages/pages.module.ts
> +    MainSpaceComponent
Clean spaces.

2023-12-11 19:10 UTC, Lukash88 commented on binder-web-frontend/src/api/model/tableFlatNode.ts
Resolved 95f1065.

2023-12-11 19:10 UTC, Lukash88 commented on binder-web-frontend/src/api/model/tableNode.ts
Resolved 95f1065.

2023-12-11 19:10 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
> +      display: inline-flex;
Resolved 95f1065.

2023-12-11 19:10 UTC, Lukash88 commented on binder-web-frontend/src/pages/pages.module.ts
> +    MainSpaceComponent
Resolved 355634b.

2023-12-11 21:24 UTC, StraykerPL approved these changes, later dismissed

2023-12-11 21:34 UTC, StraykerPL approved these changes

2023-12-11 21:36 UTC, merged