refactor(webbackend): Refactor exception's handler
StraykerPL/Binder pull request #143
Opened 2023-12-28 20:28 UTC by Lukash88

## Summary

_Provide an Overview of performed work..._

## Control List

- [x] Code formatting checked,
- [x] Coding Guidelines compliance checked,
- [ ] Documentation updated (if necessary),
- [ ] Automated tests updated (if necessary),

## Screenshots

_If your work is visual, upload screenshots here and delete this placeholder and the rest of file._

_If not, leave the following text only:_

Work under this PR is not visual, no screenshots available.

2023-12-28 21:12 UTC, StraykerPL requested changes

2023-12-28 21:12 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Extensions/ApplicationServices.cs
> +            services.AddScoped<IExceptionHandlerFactory, ExceptionHandlerFactory>();
There's no need in adding factory to IoC container - make it static class.

2023-12-28 21:12 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Extensions/ApplicationServices.cs
> +            services.AddScoped<IExceptionHandlerFactory, ExceptionHandlerFactory>();
Change class name to more descriptive about what is code doing there.

2023-12-28 21:12 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                _factory.HandleException(e, out problemDetails, context);
Try to lower down amount of arguments for factory. Exception class only is sufficient to deliver all necessary data.

2023-12-28 23:33 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Extensions/ApplicationServices.cs
> +            services.AddScoped<IExceptionHandlerFactory, ExceptionHandlerFactory>();
Resolved 64cca0b.

2023-12-28 23:33 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Extensions/ApplicationServices.cs
> +            services.AddScoped<IExceptionHandlerFactory, ExceptionHandlerFactory>();
Resolved 64cca0b.

2023-12-28 23:33 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                _factory.HandleException(e, out problemDetails, context);
Resolved 64cca0b.

2023-12-29 13:29 UTC, StraykerPL requested changes

2023-12-29 13:29 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Extensions/ApplicationServices.cs
> +using Binder.Application.Services.Middleware;
Is this using required?

2023-12-29 13:29 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                ProblemDetails? problemDetails = GetProblemDetailsByExceptionFactory.HandleException(e);
Nullability not useful here.

2023-12-29 13:29 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                await context.Response.WriteAsync(json);
Delete spaces.

2023-12-29 13:29 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/Middleware/GetProblemDetailsByExceptionFactory.cs
> +        public static ProblemDetails HandleException(Exception exception)
Make method's name more descriptive, to point it directly to factory's meaning.

2023-12-29 13:29 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Services/Middleware/GetProblemDetailsByExceptionFactory.cs
> +                    problemDetails = new ProblemDetails
No need for variable here, save operation time with "return new" here.

2023-12-29 22:32 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Extensions/ApplicationServices.cs
> +using Binder.Application.Services.Middleware;
Resolved f4a2597.

2023-12-29 22:32 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                ProblemDetails? problemDetails = GetProblemDetailsByExceptionFactory.HandleException(e);
Resolved f4a2597.

2023-12-29 22:32 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                await context.Response.WriteAsync(json);
Resolved f4a2597.

2023-12-29 22:32 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/Middleware/GetProblemDetailsByExceptionFactory.cs
> +        public static ProblemDetails HandleException(Exception exception)
Resolved f4a2597.

2023-12-29 22:32 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Services/Middleware/GetProblemDetailsByExceptionFactory.cs
> +                    problemDetails = new ProblemDetails
Resolved f4a2597.

2023-12-30 20:26 UTC, StraykerPL approved these changes

2023-12-30 20:41 UTC, merged