Allow user to add new table
StraykerPL/Binder pull request #144
Opened 2023-12-30 23:43 UTC by Lukash88

…ew table

## Summary

_Provide an Overview of performed work..._

## Control List

- [ ] Code formatting checked,
- [ ] Coding Guidelines compliance checked,
- [ ] Documentation updated (if necessary),
- [ ] Automated tests updated (if necessary),

## Screenshots

_If your work is visual, upload screenshots here and delete this placeholder and the rest of file._

_If not, leave the following text only:_

Work under this PR is not visual, no screenshots available.

2024-01-10 21:24 UTC, StraykerPL requested changes

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-backend/Binder.Api/Controllers/TablesController.cs
> +        public ActionResult<DefaultTable> Create(string tableName)
Stick to naming convention of the file - if methods have requests names, than use request name here as well.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-backend/Binder.Application/Models/Interfaces/IDefaultTableService.cs
> +        DefaultTable Create(string tableName);
Same, naming convention.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/assets/i18n/en.json
> +        "add": "Add"
You can move this to general section.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    let dialogRef = this.dialog.open(TableDialogComponent, {
Make it const.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    let dialogRef = this.dialog.open(TableDialogComponent, {
Move this settings to some providable settings object in external file.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Make proper subscription handling, like in addTable method.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +    box-shadow: 0px 0px 16px #00000025;
This Hex value has a little too many numbers, we don't need such binary precision.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +            border-radius: 0.8rem;
That's cool, but for precision you can make it PX.

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +            margin-left: 1rem;
Is it necessary to use margin? Can it be replaced with padding?

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.ts
> +    public dialogRef: MatDialogRef<TableDialogComponent>,
Is it possible to make this values private? Will dialog box still work after changes?

2024-01-10 21:24 UTC, StraykerPL commented on binder-web-frontend/src/pages/pages.module.ts
> +  entryComponents: [TableDialogComponent],
This feature is deprecated, please remove.

2024-01-11 21:34 UTC, Lukash88 commented on binder-web-backend/Binder.Api/Controllers/TablesController.cs
> +        public ActionResult<DefaultTable> Create(string tableName)
Resolved 09113b3.

2024-01-11 21:35 UTC, Lukash88 commented on binder-web-frontend/src/assets/i18n/en.json
> +        "add": "Add"
Resolved 09113b3.

2024-01-11 21:35 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    let dialogRef = this.dialog.open(TableDialogComponent, {
Resolved 09113b3.

2024-01-11 21:35 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    let dialogRef = this.dialog.open(TableDialogComponent, {
Resolved 09113b3.

2024-01-11 21:35 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Resolved 09113b3.

2024-01-11 21:35 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +    box-shadow: 0px 0px 16px #00000025;
Resolved 09113b3.

2024-01-11 21:36 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +            border-radius: 0.8rem;
Resolved 09113b3.

2024-01-11 21:36 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +            margin-left: 1rem;
Resolved 09113b3.

2024-01-11 21:36 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.ts
> +    public dialogRef: MatDialogRef<TableDialogComponent>,
Resolved 09113b3.

2024-01-11 21:36 UTC, Lukash88 commented on binder-web-frontend/src/pages/pages.module.ts
> +  entryComponents: [TableDialogComponent],
Resolved 09113b3.

2024-01-11 21:36 UTC, Lukash88 commented on binder-web-backend/Binder.Application/Models/Interfaces/IDefaultTableService.cs
> +        DefaultTable Create(string tableName);
Resolved 09113b3.

2024-01-12 20:35 UTC, StraykerPL commented on binder-web-frontend/src/assets/i18n/en.json
> +        "add": "Add"
I meant only the commented line :)

2024-01-12 20:41 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Missing unsubscribe handling.

2024-01-12 20:44 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +            border-radius: 0.8rem;
Again, I meant only border-radius line ;)

2024-01-12 20:51 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.ts
> +    public dialogRef: MatDialogRef<TableDialogComponent>,
I meant both values in constructor, that's why I used plural "values" word ;)

2024-01-12 20:59 UTC, StraykerPL requested changes

2024-01-12 20:59 UTC, StraykerPL commented on binder-web-frontend/src/app/app.module.ts
> +    FormsModule,
Double importing of FormsModule, in app.module and pages.module. Is it intended?

2024-01-12 20:59 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +import { TableDialogComponent } from '../table-dialog/table-dialog.component';
Make this import absolute-pathed.

2024-01-12 20:59 UTC, StraykerPL commented on binder-web-frontend/src/shared/consts/appConsts.ts
> +  position: { top: '30vh', left: '50vw' },
It appeared, that Angular Material will center dialogbox automatically without position value in config - so you can remove it.

2024-01-12 20:59 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.ts
> +  selector: 'app-table-dialog',
Remove selector's prefix.

2024-01-13 21:55 UTC, Lukash88 commented on binder-web-frontend/src/assets/i18n/en.json
> +        "add": "Add"
Resolved 956ff6a6a.

2024-01-13 21:55 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.scss
> +            border-radius: 0.8rem;
Resolved 956ff6a6a.

2024-01-13 21:55 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.ts
> +    public dialogRef: MatDialogRef<TableDialogComponent>,
Resolved 956ff6a6a.

2024-01-13 21:55 UTC, Lukash88 commented on binder-web-frontend/src/app/app.module.ts
> +    FormsModule,
Resolved 956ff6a6a.

2024-01-13 21:56 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +import { TableDialogComponent } from '../table-dialog/table-dialog.component';
Resolved 956ff6a6a.

2024-01-13 21:56 UTC, Lukash88 commented on binder-web-frontend/src/shared/consts/appConsts.ts
> +  position: { top: '30vh', left: '50vw' },
Resolved 956ff6a6a.

2024-01-13 21:56 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/table-dialog/table-dialog.component.ts
> +  selector: 'app-table-dialog',
Resolved 956ff6a6a.

2024-01-13 21:56 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +    dialogRef.afterClosed().subscribe((result) => {
Resolved 956ff6a6a.

2024-01-13 22:52 UTC, StraykerPL approved these changes

2024-01-13 23:04 UTC, merged