Allow user to add and display task
StraykerPL/Binder pull request #147
Opened 2024-01-17 20:50 UTC by Lukash88

## Summary

_Provide an Overview of performed work..._

## Control List

- [ ] Code formatting checked,
- [ ] Coding Guidelines compliance checked,
- [ ] Documentation updated (if necessary),
- [ ] Automated tests updated (if necessary),

## Screenshots

_If your work is visual, upload screenshots here and delete this placeholder and the rest of file._

_If not, leave the following text only:_

Work under this PR is not visual, no screenshots available.

2024-01-28 22:13 UTC, StraykerPL requested changes

2024-01-28 22:13 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +import { TaskDialogComponent } from '../task-dialog/task-dialog.component';
Change to absolute path

2024-01-28 22:13 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +          console.log(result);
Remove logging.

2024-01-28 22:13 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/task-dialog/task-dialog.component.scss
Too many percentages on width/height values. Is it possible to replace someof them?

2024-01-28 22:38 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/task-dialog/task-dialog.component.scss
Discussed internally.

2024-01-29 21:10 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +import { TaskDialogComponent } from '../task-dialog/task-dialog.component';
Resolved 6b16d83.

2024-01-29 21:11 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.ts
> +          console.log(result);
Resolved 6b16d83.

2024-01-29 21:11 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/task-dialog/task-dialog.component.scss
Resolved 6b16d83.

2024-01-29 22:44 UTC, StraykerPL approved these changes

2024-01-29 23:02 UTC, merged