Create env_issue_template.md
StraykerPL/Binder pull request #26
Opened 2023-02-14 18:39 UTC by marekksiazek

Add new issue template with environment.

2023-02-22 19:46 UTC, StraykerPL requested changes

2023-02-22 19:46 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/env_issue_template.md
> +labels: environment, settings
We don't have such labels, please remove.

2023-02-22 19:46 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/env_issue_template.md
> +name: Environment issue
Make "issue" word "Issue".

2023-02-22 19:46 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/env_issue_template.md
> +**What env do you have?**
Add environments options list here: dev, test, prod.

2023-02-22 19:47 UTC, StraykerPL commented
Please update branch.

2023-02-23 14:00 UTC, marekksiazek reviewed
Corrected

2023-02-23 20:46 UTC, StraykerPL requested changes

2023-02-23 20:46 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/env_issue_template.md
> +labels: settings
We don't have "settings" label, please remove

2023-02-23 20:50 UTC, marekksiazek reviewed
Delete labels

2023-02-23 21:01 UTC, StraykerPL approved these changes

2023-02-23 21:02 UTC, merged