Issue templates
StraykerPL/Binder pull request #33
Opened 2023-02-22 17:47 UTC by marekksiazek

## Summary

Refactor issue templates

## Details

Remove double bug_report file. Add two new files (refactor_request and test_request)

2023-02-22 20:01 UTC, StraykerPL requested changes

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +about: Create a report to help us improve
"[...] improve our code base."

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +name: Bug report
"Refactor Request"

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +title: ""
"Refactor: here describe request shortly"

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +assignees: ""
@StraykerPL

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +_improve the design, structure and implementation of software or improves code readability and reduces complexities or else_
"of software or improve [...] and reduce complexity etc.

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +1.
Change to bulleted list.

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +name: Bug report
"Test Request"

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +about: Create a report to help us improve
"Request to perform testing on dev/test environments."

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +title: ""
"Test: here describe shortly what is to be tested"

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +labels: ""
"testing"

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +assignees: ""
@StraykerPL

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +Author:
No need for "Author:" word, just leave space for tagging.

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +### Feature description
Change to "Tickets involved" and make space for tagging tickets.

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +### What should be the result
Bugs will be the results :) No need for this section

2023-02-22 20:01 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +### Requirements to run
Better to write "Reproduction steps (optional)" here with numbered list to describe how to reproduce eg. bug showup.

2023-02-23 14:23 UTC, marekksiazek reviewed
Corrected

2023-02-23 21:00 UTC, StraykerPL requested changes

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +title: ""
This comment was marked as resolved, but no change was made.

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +labels: ""
Add "refactor" label

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +assignees: StraykerPL https://github.com/StraykerPL
Just nickname, no need for URL

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +refactor: here describe request shortly
This is not right, please delete and move it to "title".

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +_improve the design, structure and implementation of software or improve code readability and reduces complexitiy etc._
"[...]reduce[...]"

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +test: here describe shortly what is to be tested
This should be under "title" variable.

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +assignees: StraykerPL https://github.com/StraykerPL
Just nickname.

2023-02-23 21:00 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +Requirements:
So what exactly will be these "requirements"?

2023-02-24 17:39 UTC, marekksiazek reviewed
Corrected

2023-02-25 23:56 UTC, StraykerPL requested changes

2023-02-25 23:56 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +labels: "Refactor"
Just "refactor" word, just like issue labels on GitHub

2023-02-25 23:56 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/refactor_request.md
> +title: Here describe request shortly
This all line should be: "title: Refactor: Here describe request shortly"

2023-02-25 23:56 UTC, StraykerPL commented on .github/ISSUE_TEMPLATE/test_request.md
> +title: Here describe shortly what is to be tested
Just like in refactor template file: "title: Test: Here describe shortly what is to be tested"

2023-02-26 20:41 UTC, StraykerPL approved these changes

2023-02-26 20:41 UTC, merged