Readme update
StraykerPL/Binder pull request #34
Opened 2023-02-22 18:34 UTC by marekksiazek

## Summary

Update readme

## Details

Change README content. Add some items like badges and change text.

2023-02-22 20:05 UTC, StraykerPL commented
Some changes are shared with other branch, please watch out for this situation in future as this is dangerous:
![image](https://user-images.githubusercontent.com/45916090/220746748-c91d70b1-eb7f-4a25-b54c-dee4e850c508.png)

2023-02-22 20:07 UTC, StraykerPL commented
Hehe XD
![image](https://user-images.githubusercontent.com/45916090/220747317-325c701f-3bda-4d7e-b776-a0f4ff834c72.png)

2023-02-22 20:11 UTC, StraykerPL requested changes

2023-02-22 20:11 UTC, StraykerPL commented on README.md
> +Cross-platform solution for **task-oriented data management**, supporting **Windows, Linux, macOS, Android and iOS**.
This formatting is not working:
![image](https://user-images.githubusercontent.com/45916090/220747463-5b57519d-7f8d-40ff-8122-0489543ddfc1.png)

2023-02-23 14:28 UTC, marekksiazek reviewed
Corrected

2023-02-26 00:06 UTC, StraykerPL requested changes

2023-02-26 00:06 UTC, StraykerPL commented on README.md
> +- [Getting Started][quickstart]
Link redirection syntax in Markdown is: [My Website](https://straykersoftware.pl)

2023-02-26 00:06 UTC, StraykerPL commented on README.md
> +- [Getting Started][quickstart]
Check once more the order of elements in ticket and rearrange them in ReadMe

2023-02-26 00:06 UTC, StraykerPL commented on README.md
> +- [Getting Started][quickstart]
Every dot in ticket is one section in ReadMe, sections' titles should be in table of content.

2023-02-26 00:06 UTC, StraykerPL commented on README.md
> +- [Getting Started][quickstart]
Tech Stack is missing.

2023-02-26 00:06 UTC, StraykerPL commented on README.md
> +- [Getting Started][quickstart]
Contribution Guidelines are missing.

2023-02-26 21:20 UTC, marekksiazek reviewed
Corrected

2023-02-26 22:00 UTC, StraykerPL approved these changes

2023-02-26 22:00 UTC, merged