feat: Added global handling middleware
StraykerPL/Binder pull request #41
Opened 2023-02-28 17:28 UTC by Hubertgitck

Summary
Added global handling middleware.

Details
Global handling middleware which handles all unhandled errors. Middleware is returning ProblemDetails ( according to RFC 7807 ) response which is serialized to Json format. Handler is able to be extended with new custom exceptions which MUST inherti Exception class.

References
[RFC 7807](https://www.rfc-editor.org/rfc/rfc7807)

2023-03-01 19:54 UTC, StraykerPL requested changes

2023-03-01 19:54 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/CustomExceptions/NotFoundException.cs
> +﻿namespace Binder.Application.Services.Middleware.CustomExceptions;
Use casual namespace declaration.

2023-03-01 19:54 UTC, StraykerPL commented on binder-backend/Binder.Api/Program.cs
> +
Is this line necessary?

2023-03-01 19:54 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +
Add casual namespace declaration.

2023-03-01 19:54 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    Title = "Invalid operation!",
This strings will be returned to output, make const file for them in Core layer.

2023-03-01 19:54 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    Title = "Resource not found!",
Like higher.

2023-03-01 19:54 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    Title = "An unexpected error occurred!",
Like higher.

2023-03-01 19:54 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +            context.Response.ContentType = "application/problem+json";
Move string to const field.

2023-03-01 19:55 UTC, StraykerPL commented
Please update PR's data: Assignees, Labels and ticket connection.

2023-03-02 17:31 UTC, Hubertgitck commented on binder-backend/Binder.Api/Program.cs
> +
No, i removed it.

2023-03-02 17:49 UTC, Hubertgitck commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +
Changed to casual declaration

2023-03-02 17:49 UTC, Hubertgitck commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    Title = "Invalid operation!",
Added file in core layer with const strings for exception titles.

2023-03-02 17:49 UTC, Hubertgitck commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    Title = "Resource not found!",
Added file in core layer with const strings for exception titles.

2023-03-02 17:49 UTC, Hubertgitck commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                    Title = "An unexpected error occurred!",
Added file in core layer with const strings for exception titles.

2023-03-02 17:50 UTC, Hubertgitck commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +            context.Response.ContentType = "application/problem+json";
Added file in core layer with const strings for exception titles.

2023-03-02 19:27 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +            context.Response.ContentType = "application/problem+json";
This comment is marked as resolved, but change was not preformed, please correct the mistake.

2023-03-02 19:29 UTC, StraykerPL commented
Please re-request review if work over this PR is finished.

2023-03-02 20:01 UTC, Hubertgitck commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +            context.Response.ContentType = "application/problem+json";
Sorry, corrected.

2023-03-02 20:19 UTC, StraykerPL requested changes

2023-03-02 20:19 UTC, StraykerPL commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                context.Response.ContentType = ExceptionConstants.ProblemJsonType;
In previous comment I marked it to move this value to "const field" not into domain area. Please, next time read comment carefully before performing changes.

2023-03-02 21:37 UTC, Hubertgitck commented on binder-backend/Binder.Application/Services/Middleware/ErrorHandlingMiddleware.cs
> +                context.Response.ContentType = ExceptionConstants.ProblemJsonType;
Moved to private const field.

2023-03-04 22:07 UTC, StraykerPL approved these changes

2023-03-04 22:08 UTC, merged