feat: add app navbar wihout logic
StraykerPL/Binder pull request #42
Opened 2023-03-01 11:32 UTC by XmatmatiX

## Summary

Add navbar component to frontend project.

## Details

Navbar component contains Angular material components: mat-button-toggle and mat-button-toggle-group
Component has rounded border, is fixed and have width set to max-width in .scss file

2023-03-01 20:15 UTC, StraykerPL requested changes

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/app.module.ts
> +import {MatButtonToggleModule} from '@angular/material/button-toggle';
Order up imports, from top to bottom: modules, components, services.

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +<div>
This component is Homepage-only right now, move it to home/components location.

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle-group class="navbar">
These buttons are not intented to be switchable, please refactor.

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle value="Show Completed">Show Completed</mat-button-toggle>
Remove values during refactor.

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle-group class="navbar">
Use BEM notation: https://getbem.com

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.scss
> +.navbar.mat-button-toggle-group{
Do not style like this. When compiling CSS instructions, Sass packs them all into single file, meaning if there will appear new `mat-button-toggle-group` component in `navbar` class, styles of all this components could be damaged.

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.scss
> +    position: fixed;
Keep safe distance from fixed positioning - if this is necessary, than keep it. If it's not usefull - change or remove.

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.scss
> +    width: max-content;
Can cause overflow. Please use value from mockup.

2023-03-01 20:15 UTC, StraykerPL commented on binder-web-frontend/src/app/navbar/navbar.component.spec.ts
> +describe('NavbarComponent', () => {
We are not creating unit tests for components in this project, please remove the file.

2023-03-01 20:16 UTC, StraykerPL commented
Assign yourself to this PR.

2023-03-01 20:18 UTC, StraykerPL commented
Please add real component's screenshot to PR's description.

2023-03-01 20:23 UTC, StraykerPL commented
Why "without logic"? You should prepare Input/Output data to handle every action on component.

2023-03-08 16:03 UTC, Hubertgitck commented on binder-web-frontend/src/app/app.module.ts
> +import {MatButtonToggleModule} from '@angular/material/button-toggle';
Removed, we dont need toggle buttons

2023-03-08 16:03 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +<div>
moved to home/components

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle-group class="navbar">
refactored to mat-button

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle value="Show Completed">Show Completed</mat-button-toggle>
Values removed

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +<div>
moved to home/components

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/app.module.ts
> +import {MatButtonToggleModule} from '@angular/material/button-toggle';
Removed, we dont need toggle buttons

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle-group class="navbar">
refactored to mat-button

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle value="Show Completed">Show Completed</mat-button-toggle>
Values removed

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.scss
> +.navbar.mat-button-toggle-group{
Styling removed

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.scss
> +    position: fixed;
styling removed

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.scss
> +    width: max-content;
Styling removed

2023-03-08 16:04 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.spec.ts
> +describe('NavbarComponent', () => {
Files was removed

2023-03-08 16:05 UTC, Hubertgitck commented on binder-web-frontend/src/app/navbar/navbar.component.html
> +    <mat-button-toggle-group class="navbar">
Refactored using BEM notation

2023-03-10 22:38 UTC, StraykerPL commented
Remove duplicated answer comments in conversations.

2023-03-10 22:40 UTC, StraykerPL commented
If given comment was addressed, mark it as resolved.

2023-03-10 22:40 UTC, StraykerPL commented
Only me as a reviewer.

2023-03-10 22:42 UTC, StraykerPL commented
Did you attended all the comments?

2023-03-10 22:42 UTC, StraykerPL commented
Please update branch.

2023-03-10 22:49 UTC, StraykerPL requested changes

2023-03-10 22:49 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +
Empty line?

2023-03-10 22:49 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    & button{
Use BEM, not tags.

2023-03-10 22:49 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +        padding: 0.25rem 4rem ;
"4rem ;"? Or "4rem;" ?

2023-03-10 22:49 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    & button:first-child{
Do not use CSS pseudo-class where you're not useing it's benefits. Simple BEM reference is enought in this case.

2023-03-10 22:49 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +        border-top-left-radius: 1rem;
Do not style container in it's child elements. First prepare element, next create child elements.

2023-03-10 22:49 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    & button:last-child{
This howl block of code is violating DRY rule.

2023-03-10 22:51 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.html
> +<div class="app-navbar">
Just name class "navbar", no need for namespacing here.

2023-03-10 22:52 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +        border-right: 0.05rem solid rgb(128, 128, 128, 0.5);
Use color's hash codes from Figma.

2023-03-11 08:30 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +
Removed

2023-03-11 08:31 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    & button{
Changed to BEM.

2023-03-11 08:31 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +        padding: 0.25rem 4rem ;
Whitespace deleted.

2023-03-11 08:31 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    & button:first-child{
Changed to BEM modifiers instead of pseud-classes.

2023-03-11 08:32 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +        border-top-left-radius: 1rem;
I am not styling container. Im styling child elemnts which are buttons.

2023-03-11 08:33 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    & button:last-child{
How is it vioolating DRY if one block is styling left corners and  the other right ones? Or did you mean something else than border styling?

2023-03-11 08:33 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.html
> +<div class="app-navbar">
Changed to "navbar".

2023-03-11 08:33 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +        border-right: 0.05rem solid rgb(128, 128, 128, 0.5);
Changed to Figma hash codes.

2023-03-11 08:38 UTC, Hubertgitck commented
> Please add real component's screenshot to PR's description.

2023-03-28 18:32 UTC, StraykerPL requested changes

2023-03-28 18:32 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    height: 19px;
Width and height to REM.

2023-03-30 19:11 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/navbar/navbar.component.scss
> +    height: 19px;
Refactored to rem

2023-03-31 21:18 UTC, StraykerPL approved these changes

2023-03-31 21:19 UTC, merged