Add ci-cd pipeline.
StraykerPL/Binder pull request #44
Opened 2023-03-02 18:58 UTC by KonradDyb

## Summary

Add ci-cd pipeline.

## Details

Add ci-cd pipeline basics for future development. 

## References

_Links which provides to external materials_ <br/>
[Nice guide for create CI/CD pipeline](https://www.youtube.com/watch?v=R5ppadIsGbA) 
[GitHub guide](https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/)

2023-03-02 19:35 UTC, StraykerPL requested changes

2023-03-02 19:35 UTC, StraykerPL commented on .github/workflows/ci-cd.yaml
> +name: Continous Integration and Deployment
For now it's just CI, not deploy is being performed.

2023-03-02 19:35 UTC, StraykerPL commented on .github/workflows/ci-cd.yaml
> +jobs:
Missing job for Web Frontend project prod build.

2023-03-02 19:36 UTC, StraykerPL commented
Please update PR's data: Assignees, Labels and ticket connection.

2023-03-06 17:49 UTC, KonradDyb commented on .github/workflows/ci-cd.yaml
> +name: Continous Integration and Deployment
Done.

2023-03-06 17:49 UTC, KonradDyb commented on .github/workflows/ci-cd.yaml
> +jobs:
Done.

2023-03-06 17:49 UTC, KonradDyb commented
> Please update PR's data: Assignees, Labels and ticket connection.

Done.

2023-03-06 19:44 UTC, StraykerPL requested changes

2023-03-06 19:44 UTC, StraykerPL commented on .github/workflows/pull-request.yml
> +        cache-dependency-path: binder-web-frontend/package-lock.json
Is it possible to use `env` variable here too?

2023-03-06 19:46 UTC, StraykerPL commented
Mark addressed comments conversations as resolved.

2023-03-06 19:46 UTC, StraykerPL commented
Update branch as requested by PR control.

2023-03-06 19:57 UTC, KonradDyb commented on .github/workflows/pull-request.yml
> +        cache-dependency-path: binder-web-frontend/package-lock.json
Yes it was possible :) Nice catch !

2023-03-06 20:14 UTC, StraykerPL approved these changes

2023-03-06 20:14 UTC, merged