Feature create tables list #16
StraykerPL/Binder pull request #47
Opened 2023-03-08 15:44 UTC by Hubertgitck

## Summary

Table list component for side panel

## Details

Created new component with angular material, added necessary imports.

## References

Used mat-expansion-panel https://material.angular.io/components/expansion/overview

2023-03-10 22:34 UTC, StraykerPL requested changes

2023-03-10 22:34 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
> +            <mat-panel-title class="tables-list__title">
BEM Element class should be on first child tag of BEM Block tag.

2023-03-10 22:34 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
> +          <div class="tables-list__items">
Same here.

2023-03-10 22:34 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
> +    &__items p{
Do not use tags in styling, replace with classes.

2023-03-10 22:34 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.ts
> +  panelOpenState = false;
Are you using this value somewhere?

2023-03-10 22:35 UTC, StraykerPL commented
Please add screenshot with visible component to description.

2023-03-10 22:35 UTC, StraykerPL commented
Please update the branch.

2023-03-11 08:51 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
> +            <mat-panel-title class="tables-list__title">
Refactored naming.

2023-03-11 08:51 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
> +          <div class="tables-list__items">
Refactored naming.

2023-03-11 08:52 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.scss
> +    &__items p{
Replaced with class.

2023-03-11 08:52 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.ts
> +  panelOpenState = false;
No, value removed.

2023-03-25 19:18 UTC, StraykerPL commented
Resolve conflicts.

2023-03-25 19:20 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
> +            <mat-panel-title class="tables-list__title">
This comment is not resolved.

2023-03-25 19:20 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
> +          <div class="tables-list__items">
This comment is not resolved.

2023-03-27 17:45 UTC, Hubertgitck commented on binder-web-frontend/src/pages/home/components/tables-list/tables-list.component.html
> +            <mat-panel-title class="tables-list__title">
Refactored after hints from reviewer

2023-03-28 18:44 UTC, StraykerPL approved these changes

2023-03-28 18:44 UTC, merged