feat: added_angular_theming
StraykerPL/Binder pull request #54
Opened 2023-03-25 10:58 UTC by Hubertgitck

## Summary

Implemented Angular theming

## Details

Added white and dark theme and also applied those new themes to two components: button and expansion. There is a new class applied to <body> which is "class="mat-app-background"", that applies theming to a background of our application aswell. I did renamed styles.scss to theme.scss and moved it to "shared/styles".

## References

_Links which provides to external materials_ <br/>
[Angular Theming](https://material.angular.io/guide/theming#applying-a-theme-to-components) 

![white](https://user-images.githubusercontent.com/103528563/227713091-58d1e718-d361-43e3-9350-161864abb6b3.png)
![dark](https://user-images.githubusercontent.com/103528563/227713096-ca95f01b-d2c2-4e21-b3ea-409f1d70a839.png)

2023-03-25 19:15 UTC, StraykerPL requested changes

2023-03-25 19:15 UTC, StraykerPL commented on binder-web-frontend/angular.json
> +              "src/shared/styles/theme.scss"
Make it `src/shared/styles`. Will be useful in the future.

2023-03-25 19:16 UTC, StraykerPL commented
Fill missing PR's metadata: labels.

2023-03-26 07:42 UTC, Hubertgitck commented on binder-web-frontend/angular.json
> +              "src/shared/styles/theme.scss"
Changed "src/shared/styles/theme.scss" -> "src/shared/styles.scss".

2023-03-27 17:46 UTC, StraykerPL commented on binder-web-frontend/angular.json
> +              "src/shared/styles/theme.scss"
I meant precisly `src/shared/styles` as folder, not file.

2023-03-27 17:47 UTC, StraykerPL requested changes
Reopened previous comment.

2023-03-28 14:31 UTC, Hubertgitck commented on binder-web-frontend/angular.json
> +              "src/shared/styles/theme.scss"
i made styles.scss global styles file where we will import all the other styles and left only "src/shared/styles/styles.scss" in angular.json

2023-03-31 21:20 UTC, StraykerPL requested changes

2023-03-31 21:20 UTC, StraykerPL commented on binder-web-frontend/src/shared/styles/styles.scss
> +@import 'theme.scss';
`use` instruction here. And no need to use file extension here.

2023-04-02 09:00 UTC, Hubertgitck commented on binder-web-frontend/src/shared/styles/styles.scss
> +@import 'theme.scss';
changed to @use

2023-04-02 19:16 UTC, StraykerPL approved these changes

2023-04-02 19:16 UTC, merged