Add OpenAPI Generator and fix package conflicts
StraykerPL/Binder pull request #62
Opened 2023-09-27 20:56 UTC by Lukash88

## Summary

_Provide an overview_

## Details

_Add more context to describe what changes did you do_

## References

_Links which provides to external materials_ <br/>
[Example of link](www.google.com)

2023-09-28 18:37 UTC, StraykerPL commented
Fill up PR's metadata.

2023-09-28 18:38 UTC, StraykerPL commented
Fill up PR's description.

2023-09-28 18:43 UTC, StraykerPL requested changes, later dismissed

2023-09-28 18:43 UTC, StraykerPL commented on binder-web-frontend/package.json
> +    "semver": "^7.5.4",
What this package is needed for?

2023-09-28 18:43 UTC, StraykerPL commented on binder-web-frontend/package.json
> +    "@angular-devkit/build-angular": "^15.2.9",
Is it safe to just change single package of Angular, without lifting framework version?

2023-09-28 18:43 UTC, StraykerPL commented on binder-web-frontend/package.json
> +    "gen": "openapi-generator-cli generate -g typescript-angular -i https://localhost:7183/swagger/v1/swagger.json -o ./src/api/code-gen"
Without "code-gun". Just "./src/api".

2023-10-01 19:45 UTC, StraykerPL commented
Update PR's description after content changes.

2023-10-01 19:49 UTC, StraykerPL commented
Lack of resolve info comments in conversations, reference to Wiki for more details.

2023-10-02 20:15 UTC, Lukash88 reviewed
All requested changes are addressed

2023-10-02 20:15 UTC, Lukash88 commented on binder-web-frontend/package.json
> +    "semver": "^7.5.4",
After installing **@openapitools/openapi-generator-cli** got issue with vulnerable packages. 
More about you can find [https://github.com/advisories/GHSA-c2qf-rxjj-qqgw](url)
The version in the project was "7.3.8".

2023-10-02 20:15 UTC, Lukash88 commented on binder-web-frontend/package.json
> +    "semver": "^7.5.4",
I have deleted it and changed versions of **semver** in package-lock.json

2023-10-02 20:15 UTC, Lukash88 commented on binder-web-frontend/package.json
> +    "@angular-devkit/build-angular": "^15.2.9",
It depends but in this case it was unnecessary so I downgrade the package back to previous version.

2023-10-02 20:15 UTC, Lukash88 commented on binder-web-frontend/package.json
> +    "gen": "openapi-generator-cli generate -g typescript-angular -i https://localhost:7183/swagger/v1/swagger.json -o ./src/api/code-gen"
Resolved 7a76a1c

2023-10-02 20:15 UTC, Lukash88 commented on binder-web-frontend/package.json
> +    "semver": "^7.5.4",
Resolved  e589e90

2023-10-02 20:15 UTC, Lukash88 commented on binder-web-frontend/package.json
> +    "@angular-devkit/build-angular": "^15.2.9",
Resolved  e589e90

2023-10-04 20:17 UTC, StraykerPL approved these changes

2023-10-04 20:18 UTC, merged