Feature/18 create apps header
StraykerPL/Binder pull request #64
Opened 2023-10-08 11:29 UTC by Lukash88

## Summary

App's header component has been created and added to side panel.

## Details

App's header has been added to the application's frontend and placed on newly created side panel according to page layout mockup.
Version of app is loaded dynamically.
Buttons: "Options" and "About" has been placed on the (left) side panel and align to the bottom of page.

Page layout after changes:
![image](https://github.com/Strayker-Software/Binder/assets/80634023/68de8e50-a04e-4dac-860a-04d2cf4bdf76)

Target of this ticket was to create just this component, any other work is out of scope here.

## References

No external references needed.

2023-10-08 20:06 UTC, StraykerPL commented
Disconnect PR from backlog.

2023-10-08 20:21 UTC, StraykerPL requested changes

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/home.component.html
> +<div class="container">
Out of scope work performed. Please stick to ticket's request.

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/home.component.scss
This is Web Framework - please use Sass in SCSS notation.

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/home.component.scss
Out of scope work performed. Please stick to ticket's request.

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/src/shared/components/app-header/app-header.component.html
Move component to Home page.

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/src/shared/components/app-header/app-header.component.html
> +    <h2> Binder <span>v{{version}}</span></h2>
Remove first space, add spaces between version brackets.

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/src/shared/components/app-header/app-header.component.scss
This is Web Framework - please use Sass in SCSS notation.

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/src/shared/components/app-header/app-header.component.ts
> +
Remove empty line.

2023-10-08 20:21 UTC, StraykerPL commented on binder-web-frontend/tsconfig.json
Do not change framework's config.

2023-10-08 20:43 UTC, Lukash88 commented on binder-web-frontend/src/shared/components/app-header/app-header.component.html
> +    <h2> Binder <span>v{{version}}</span></h2>
Resolved 1097a94

2023-10-08 20:53 UTC, Lukash88 commented on binder-web-frontend/src/shared/components/app-header/app-header.component.ts
> +
Resolved cecbfb5

2023-10-08 21:22 UTC, Lukash88 commented on binder-web-frontend/src/shared/components/app-header/app-header.component.html
Resolved 230ec33

2023-10-08 21:29 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/home.component.html
> +<div class="container">
Resolved 2f3505b

2023-10-08 21:51 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/home.component.scss
Resolved ce6188d

2023-10-08 21:51 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/home.component.scss
Resolved ce6188d

2023-10-08 22:11 UTC, Lukash88 commented on binder-web-frontend/src/shared/components/app-header/app-header.component.scss
Resolved bfa3eee

2023-10-09 19:11 UTC, StraykerPL requested changes

2023-10-09 19:11 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.html
> +    <h2>Binder <span>v{{ version }}</span></h2>
Switch styling from tag to style sheet.

2023-10-09 19:11 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.scss
> +div {
Do not use tags, replace with BEM classes.

2023-10-09 19:11 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.ts
> +import  packageInfo  from 'package.json';
Remove.

2023-10-09 19:11 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.ts
> +   version: any = packageInfo.version;
Make version of type number, mock value.

2023-10-09 19:11 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.ts
> +  selector: 'app-header',
Remove prefix from component.

2023-10-09 19:11 UTC, StraykerPL commented on binder-web-frontend/src/pages/pages.module.ts
If component is in Home page component, declare it in page's module, not the shared one.

2023-10-09 20:24 UTC, Lukash88 commented on binder-web-frontend/tsconfig.json
Resolved b988762

2023-10-11 19:07 UTC, Lukash88 commented on binder-web-frontend/src/pages/pages.module.ts
Resolved 8d54cc3

2023-10-11 19:07 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.ts
> +  selector: 'app-header',
Resolved 8d54cc3

2023-10-11 19:07 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.ts
> +   version: any = packageInfo.version;
Resolved 8d54cc3

2023-10-11 19:07 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.ts
> +import  packageInfo  from 'package.json';
Resolved 8d54cc3

2023-10-11 19:07 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.scss
> +div {
Resolved 8d54cc3

2023-10-11 19:07 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/app-header/app-header.component.html
> +    <h2>Binder <span>v{{ version }}</span></h2>
Resolved 8d54cc3

2023-10-11 19:49 UTC, StraykerPL requested changes

2023-10-11 19:49 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/header/header.component.scss
> +    border-bottom: solid 0.2rem #fff;
Change color code to default, 6-char length.

2023-10-11 19:49 UTC, StraykerPL commented on binder-web-frontend/src/shared/components/.gitkeep
If folder stays empty, do not delete this file.

2023-10-11 19:58 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/header/header.component.scss
> +    border-bottom: solid 0.2rem #fff;
Resolved 483cd16

2023-10-11 20:10 UTC, Lukash88 commented on binder-web-frontend/src/shared/components/.gitkeep
Resolved 48714c9

2023-10-11 20:37 UTC, StraykerPL approved these changes

2023-10-11 20:39 UTC, merged