Feature/80 allow web frontend to load apps version from web backend
StraykerPL/Binder pull request #87
Opened 2023-10-23 21:38 UTC by Lukash88

## Summary

The app's version is now loaded dynamically from Web Backend.

## Details

It is an ambiguous reference between `Version` and `System.Version` so entity calls `AppVersion`.

- Create Version entity on Web Backend, with Major, Minor, Patch and Name properties,
- Make Repository, Service and Controller class for AppVersion
- Replace mocked value with the one returned from Web Backend

**Screenshot:**

![image](https://github.com/Strayker-Software/Binder/assets/80634023/72e3ad4c-995e-4962-a21a-423409f51dc2)

## References

No external references needed.

2023-10-25 21:41 UTC, StraykerPL requested changes

2023-10-25 21:41 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/header/header.component.html
> +    </p>
Move this tag back to upper line.

2023-10-25 21:41 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +  attributes: string[] = ['major', 'minor', 'patch', 'name'];
Are this values used somewhere?

2023-10-25 21:41 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +  //version?: DisplayableVersion;
Remove comment, if not used.

2023-10-25 21:41 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +      .pipe(take(1))
Connect subscription control here.

2023-10-25 21:41 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +
Clean up code.

2023-10-25 21:59 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/header/header.component.html
> +    </p>
Resolved 6b25ad1

2023-10-25 22:00 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +  //version?: DisplayableVersion;
Resolved 6b25ad1

2023-10-25 22:00 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +  attributes: string[] = ['major', 'minor', 'patch', 'name'];
Resolved 6b25ad1

2023-10-25 22:00 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +
Resolved 6b25ad1

2023-10-25 22:01 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +      .pipe(take(1))
Resolved 6b25ad1

2023-10-25 22:06 UTC, StraykerPL requested changes

2023-10-25 22:06 UTC, StraykerPL commented on binder-web-backend/Binder.Persistence/Migrations/20231022154458_AddAppVersionEntity.Designer.cs
Clean up migrations, this version value is not in DB anymore.

2023-10-25 22:06 UTC, StraykerPL commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +  version?: string;
Make this value non-nullable, add value on definition's level.

2023-10-26 20:26 UTC, Lukash88 commented on binder-web-backend/Binder.Persistence/Migrations/20231022154458_AddAppVersionEntity.Designer.cs
Resolved 1c21729

2023-10-26 20:27 UTC, Lukash88 commented on binder-web-frontend/src/pages/home/components/header/header.component.ts
> +  version?: string;
Resolved 09b64a7

2023-10-26 20:50 UTC, StraykerPL approved these changes

2023-10-26 20:51 UTC, merged